pluginManagement {
	repositories {
		mavenLocal()
		gradlePluginPortal()
		maven { 
			url = "https://maven.fabricmc.net/"
			metadataSources {
				mavenPom()
				artifact()
			}
		}
		maven {
			url = "https://maven.neoforged.net/releases"
		}
		mavenCentral()
	}
	resolutionStrategy {
		eachPlugin {
			if (it.requested.id.namespace == 'fabric-loom') {
				it.useModule("net.fabricmc:fabric-loom:${it.requested.version}")
			}
		}
	}
}

rootProject.name = "fluttershyvisual"
